# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_completion_request import ChatCompletionRequest
from ..types.chat_completion_response import ChatCompletionResponse
from ..types.success_response import SuccessResponse
from .raw_client import AsyncRawChatClient, RawChatClient
from .types.get_chat_completion_response import GetChatCompletionResponse
from .types.list_chat_completions_response import ListChatCompletionsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChatClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChatClient
        """
        return self._raw_client

    def list_chat_completions(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        agent_id: typing.Optional[str] = None,
        channel_id: typing.Optional[str] = None,
        bible_id: typing.Optional[str] = None,
        cached: typing.Optional[str] = None,
        client: typing.Optional[str] = None,
        config_id: typing.Optional[str] = None,
        conversation_id: typing.Optional[str] = None,
        device_id: typing.Optional[str] = None,
        flagged: typing.Optional[str] = None,
        favorited: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        liked: typing.Optional[str] = None,
        session_id: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatCompletionsResponse:
        """
        Returns a paginated list of chat completions (prompts) for the agent, with applied tags expanded as { id, name } and share metadata.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        agent_id : typing.Optional[str]

        channel_id : typing.Optional[str]

        bible_id : typing.Optional[str]

        cached : typing.Optional[str]

        client : typing.Optional[str]

        config_id : typing.Optional[str]

        conversation_id : typing.Optional[str]

        device_id : typing.Optional[str]

        flagged : typing.Optional[str]

        favorited : typing.Optional[str]

        language : typing.Optional[str]

        liked : typing.Optional[str]

        session_id : typing.Optional[str]

        user_id : typing.Optional[str]

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatCompletionsResponse
            Paginated list of chat completions

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.list_chat_completions()
        """
        _response = self._raw_client.list_chat_completions(
            page=page,
            per_page=per_page,
            agent_id=agent_id,
            channel_id=channel_id,
            bible_id=bible_id,
            cached=cached,
            client=client,
            config_id=config_id,
            conversation_id=conversation_id,
            device_id=device_id,
            flagged=flagged,
            favorited=favorited,
            language=language,
            liked=liked,
            session_id=session_id,
            user_id=user_id,
            min_timestamp=min_timestamp,
            max_timestamp=max_timestamp,
            request_options=request_options,
        )
        return _response.data

    def create_chat_completion(
        self, *, request: ChatCompletionRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ChatCompletionResponse:
        """
        Creates a chat completion using the agent's configured model. Supports both streaming and non-streaming responses.

        Parameters
        ----------
        request : ChatCompletionRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChatCompletionResponse
            Successful response

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.create_chat_completion(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create_chat_completion(request=request, request_options=request_options)
        return _response.data

    def like_completion(
        self, id: str, *, liked: bool, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Updates the like status of a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        liked : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Like successfully logged

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.like_completion(
            id="id",
            liked=True,
        )
        """
        _response = self._raw_client.like_completion(id, liked=liked, request_options=request_options)
        return _response.data

    def flag_completion(
        self, id: str, *, flagged: bool, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Updates the flagged status of a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        flagged : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Response successfully flagged

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.flag_completion(
            id="id",
            flagged=True,
        )
        """
        _response = self._raw_client.flag_completion(id, flagged=flagged, request_options=request_options)
        return _response.data

    def feedback_completion(
        self, id: str, *, feedback: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Adds user feedback to a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        feedback : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Feedback successfully logged

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.feedback_completion(
            id="id",
            feedback="feedback",
        )
        """
        _response = self._raw_client.feedback_completion(id, feedback=feedback, request_options=request_options)
        return _response.data

    def share_completion(
        self,
        id: str,
        *,
        conversation_id: typing.Optional[str] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Creates a share record for a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        conversation_id : typing.Optional[str]

        session_id : typing.Optional[str]

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Share successfully logged

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.share_completion(
            id="id",
        )
        """
        _response = self._raw_client.share_completion(
            id, conversation_id=conversation_id, session_id=session_id, user_id=user_id, request_options=request_options
        )
        return _response.data

    def get_chat_completion(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetChatCompletionResponse:
        """
        Returns a single chat completion (prompt) by numeric id or UUID, including applied tags, guardrail/cta metadata, share metadata, and automation results.

        Parameters
        ----------
        id : str
            The numeric id or UUID of the chat completion

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetChatCompletionResponse
            The chat completion

        Examples
        --------
        from apologist import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.chat.get_chat_completion(
            id="id",
        )
        """
        _response = self._raw_client.get_chat_completion(id, request_options=request_options)
        return _response.data


class AsyncChatClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChatClient
        """
        return self._raw_client

    async def list_chat_completions(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        agent_id: typing.Optional[str] = None,
        channel_id: typing.Optional[str] = None,
        bible_id: typing.Optional[str] = None,
        cached: typing.Optional[str] = None,
        client: typing.Optional[str] = None,
        config_id: typing.Optional[str] = None,
        conversation_id: typing.Optional[str] = None,
        device_id: typing.Optional[str] = None,
        flagged: typing.Optional[str] = None,
        favorited: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        liked: typing.Optional[str] = None,
        session_id: typing.Optional[str] = None,
        user_id: typing.Optional[str] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListChatCompletionsResponse:
        """
        Returns a paginated list of chat completions (prompts) for the agent, with applied tags expanded as { id, name } and share metadata.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        agent_id : typing.Optional[str]

        channel_id : typing.Optional[str]

        bible_id : typing.Optional[str]

        cached : typing.Optional[str]

        client : typing.Optional[str]

        config_id : typing.Optional[str]

        conversation_id : typing.Optional[str]

        device_id : typing.Optional[str]

        flagged : typing.Optional[str]

        favorited : typing.Optional[str]

        language : typing.Optional[str]

        liked : typing.Optional[str]

        session_id : typing.Optional[str]

        user_id : typing.Optional[str]

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListChatCompletionsResponse
            Paginated list of chat completions

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.list_chat_completions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_chat_completions(
            page=page,
            per_page=per_page,
            agent_id=agent_id,
            channel_id=channel_id,
            bible_id=bible_id,
            cached=cached,
            client=client,
            config_id=config_id,
            conversation_id=conversation_id,
            device_id=device_id,
            flagged=flagged,
            favorited=favorited,
            language=language,
            liked=liked,
            session_id=session_id,
            user_id=user_id,
            min_timestamp=min_timestamp,
            max_timestamp=max_timestamp,
            request_options=request_options,
        )
        return _response.data

    async def create_chat_completion(
        self, *, request: ChatCompletionRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ChatCompletionResponse:
        """
        Creates a chat completion using the agent's configured model. Supports both streaming and non-streaming responses.

        Parameters
        ----------
        request : ChatCompletionRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChatCompletionResponse
            Successful response

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.create_chat_completion(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_chat_completion(request=request, request_options=request_options)
        return _response.data

    async def like_completion(
        self, id: str, *, liked: bool, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Updates the like status of a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        liked : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Like successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.like_completion(
                id="id",
                liked=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.like_completion(id, liked=liked, request_options=request_options)
        return _response.data

    async def flag_completion(
        self, id: str, *, flagged: bool, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Updates the flagged status of a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        flagged : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Response successfully flagged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.flag_completion(
                id="id",
                flagged=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.flag_completion(id, flagged=flagged, request_options=request_options)
        return _response.data

    async def feedback_completion(
        self, id: str, *, feedback: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Adds user feedback to a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        feedback : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Feedback successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.feedback_completion(
                id="id",
                feedback="feedback",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.feedback_completion(id, feedback=feedback, request_options=request_options)
        return _response.data

    async def share_completion(
        self,
        id: str,
        *,
        conversation_id: typing.Optional[str] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Creates a share record for a specific chat completion

        Parameters
        ----------
        id : str
            The ID of the chat completion

        conversation_id : typing.Optional[str]

        session_id : typing.Optional[str]

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Share successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.share_completion(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.share_completion(
            id, conversation_id=conversation_id, session_id=session_id, user_id=user_id, request_options=request_options
        )
        return _response.data

    async def get_chat_completion(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetChatCompletionResponse:
        """
        Returns a single chat completion (prompt) by numeric id or UUID, including applied tags, guardrail/cta metadata, share metadata, and automation results.

        Parameters
        ----------
        id : str
            The numeric id or UUID of the chat completion

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetChatCompletionResponse
            The chat completion

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.get_chat_completion(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_chat_completion(id, request_options=request_options)
        return _response.data
