# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CorpusSearchRequestFilters(UniversalBaseModel):
    model: typing.Optional[str] = None
    ids: typing.Optional[typing.List[int]] = None
    types: typing.Optional[typing.List[str]] = None
    languages: typing.Optional[typing.List[str]] = None
    collection_ids: typing.Optional[typing.List[int]] = None
    contributor_ids: typing.Optional[typing.List[int]] = None
    category_ids: typing.Optional[typing.List[int]] = None
    classification_ids: typing.Optional[typing.List[int]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
