# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgentClient, RawAgentClient
from .types.pause_agent_response import PauseAgentResponse
from .types.resume_agent_response import ResumeAgentResponse


class AgentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentClient
        """
        return self._raw_client

    def pause_agent(self, *, request_options: typing.Optional[RequestOptions] = None) -> PauseAgentResponse:
        """
        Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PauseAgentResponse
            Agent paused

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.agent.pause_agent()
        """
        _response = self._raw_client.pause_agent(request_options=request_options)
        return _response.data

    def resume_agent(self, *, request_options: typing.Optional[RequestOptions] = None) -> ResumeAgentResponse:
        """
        Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResumeAgentResponse
            Agent resumed

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.agent.resume_agent()
        """
        _response = self._raw_client.resume_agent(request_options=request_options)
        return _response.data


class AsyncAgentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentClient
        """
        return self._raw_client

    async def pause_agent(self, *, request_options: typing.Optional[RequestOptions] = None) -> PauseAgentResponse:
        """
        Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PauseAgentResponse
            Agent paused

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent.pause_agent()


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_agent(request_options=request_options)
        return _response.data

    async def resume_agent(self, *, request_options: typing.Optional[RequestOptions] = None) -> ResumeAgentResponse:
        """
        Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResumeAgentResponse
            Agent resumed

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent.resume_agent()


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_agent(request_options=request_options)
        return _response.data
