# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawUsersClient, RawUsersClient
from .types.anonymize_user_response import AnonymizeUserResponse
from .types.get_user_response import GetUserResponse
from .types.list_user_flags_response import ListUserFlagsResponse
from .types.list_users_response import ListUsersResponse
from .types.scrub_user_response import ScrubUserResponse
from .types.update_user_response import UpdateUserResponse
from .types.user_update_request_tags_item import UserUpdateRequestTagsItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UsersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUsersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUsersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUsersClient
        """
        return self._raw_client

    def list_users(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        external_id: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        responder_id: typing.Optional[str] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUsersResponse:
        """
        Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        external_id : typing.Optional[str]

        tags : typing.Optional[str]
            Comma-separated tag ids.

        responder_id : typing.Optional[str]

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUsersResponse
            Paginated list of users

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.users.list_users()
        """
        _response = self._raw_client.list_users(
            page=page,
            per_page=per_page,
            external_id=external_id,
            tags=tags,
            responder_id=responder_id,
            min_timestamp=min_timestamp,
            max_timestamp=max_timestamp,
            request_options=request_options,
        )
        return _response.data

    def list_user_flags(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserFlagsResponse:
        """
        Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserFlagsResponse
            Paginated list of user flag definitions

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.users.list_user_flags()
        """
        _response = self._raw_client.list_user_flags(page=page, per_page=per_page, request_options=request_options)
        return _response.data

    def get_user(self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetUserResponse:
        """
        Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUserResponse
            The user

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.users.get_user(
            user_id="user_id",
        )
        """
        _response = self._raw_client.get_user(user_id, request_options=request_options)
        return _response.data

    def update_user(
        self,
        user_id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        tags: typing.Optional[typing.Sequence[UserUpdateRequestTagsItem]] = OMIT,
        responder_id: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateUserResponse:
        """
        Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        external_id : typing.Optional[str]
            Your external identifier for the user.

        tags : typing.Optional[typing.Sequence[UserUpdateRequestTagsItem]]
            Applied tags as a mix of existing tag ids and/or default-language tag names. Unknown ids or names are rejected. Tags are mirror-owned and never created here.

        responder_id : typing.Optional[int]
            Responder to persist for this user on the requesting agent. Must be active on the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateUserResponse
            The updated user

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.users.update_user(
            user_id="user_id",
        )
        """
        _response = self._raw_client.update_user(
            user_id, external_id=external_id, tags=tags, responder_id=responder_id, request_options=request_options
        )
        return _response.data

    def scrub_user(self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ScrubUserResponse:
        """
        Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScrubUserResponse
            Scrub progress for the user

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.users.scrub_user(
            user_id="user_id",
        )
        """
        _response = self._raw_client.scrub_user(user_id, request_options=request_options)
        return _response.data

    def anonymize_user(
        self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AnonymizeUserResponse:
        """
        Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnonymizeUserResponse
            Anonymize progress for the user

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.users.anonymize_user(
            user_id="user_id",
        )
        """
        _response = self._raw_client.anonymize_user(user_id, request_options=request_options)
        return _response.data


class AsyncUsersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUsersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUsersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUsersClient
        """
        return self._raw_client

    async def list_users(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        external_id: typing.Optional[str] = None,
        tags: typing.Optional[str] = None,
        responder_id: typing.Optional[str] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUsersResponse:
        """
        Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        external_id : typing.Optional[str]

        tags : typing.Optional[str]
            Comma-separated tag ids.

        responder_id : typing.Optional[str]

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUsersResponse
            Paginated list of users

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.list_users()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_users(
            page=page,
            per_page=per_page,
            external_id=external_id,
            tags=tags,
            responder_id=responder_id,
            min_timestamp=min_timestamp,
            max_timestamp=max_timestamp,
            request_options=request_options,
        )
        return _response.data

    async def list_user_flags(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserFlagsResponse:
        """
        Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserFlagsResponse
            Paginated list of user flag definitions

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.list_user_flags()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_user_flags(
            page=page, per_page=per_page, request_options=request_options
        )
        return _response.data

    async def get_user(
        self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetUserResponse:
        """
        Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUserResponse
            The user

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.get_user(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_user(user_id, request_options=request_options)
        return _response.data

    async def update_user(
        self,
        user_id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        tags: typing.Optional[typing.Sequence[UserUpdateRequestTagsItem]] = OMIT,
        responder_id: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateUserResponse:
        """
        Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        external_id : typing.Optional[str]
            Your external identifier for the user.

        tags : typing.Optional[typing.Sequence[UserUpdateRequestTagsItem]]
            Applied tags as a mix of existing tag ids and/or default-language tag names. Unknown ids or names are rejected. Tags are mirror-owned and never created here.

        responder_id : typing.Optional[int]
            Responder to persist for this user on the requesting agent. Must be active on the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateUserResponse
            The updated user

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.update_user(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_user(
            user_id, external_id=external_id, tags=tags, responder_id=responder_id, request_options=request_options
        )
        return _response.data

    async def scrub_user(
        self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ScrubUserResponse:
        """
        Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScrubUserResponse
            Scrub progress for the user

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.scrub_user(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.scrub_user(user_id, request_options=request_options)
        return _response.data

    async def anonymize_user(
        self, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AnonymizeUserResponse:
        """
        Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.

        Parameters
        ----------
        user_id : str
            The user's external id or internal id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnonymizeUserResponse
            Anonymize progress for the user

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.anonymize_user(
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.anonymize_user(user_id, request_options=request_options)
        return _response.data
