# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .chat_completion_request import ChatCompletionRequest
    from .chat_completion_request_logprobs import ChatCompletionRequestLogprobs
    from .chat_completion_request_metadata import ChatCompletionRequestMetadata
    from .chat_completion_request_reasoning_effort import ChatCompletionRequestReasoningEffort
    from .chat_completion_request_response_format import ChatCompletionRequestResponseFormat
    from .chat_completion_request_response_format_json_schema import ChatCompletionRequestResponseFormatJsonSchema
    from .chat_completion_request_response_format_type import ChatCompletionRequestResponseFormatType
    from .chat_completion_request_tool_choice import ChatCompletionRequestToolChoice
    from .chat_completion_request_tool_choice_zero import ChatCompletionRequestToolChoiceZero
    from .chat_completion_request_verbosity import ChatCompletionRequestVerbosity
    from .chat_completion_response import ChatCompletionResponse
    from .chat_completion_response_choices_item import ChatCompletionResponseChoicesItem
    from .chat_completion_response_usage import ChatCompletionResponseUsage
    from .chat_message import ChatMessage
    from .chat_message_role import ChatMessageRole
    from .cta_match_request import CtaMatchRequest
    from .error import Error
    from .success_response import SuccessResponse
    from .tag_ref import TagRef
    from .user import User
    from .user_flag import UserFlag
    from .webhook_agent_ref import WebhookAgentRef
    from .webhook_cta import WebhookCta
    from .webhook_evaluation import WebhookEvaluation
    from .webhook_event_info import WebhookEventInfo
    from .webhook_event_info_key import WebhookEventInfoKey
    from .webhook_named_ref import WebhookNamedRef
    from .webhook_notification_ref import WebhookNotificationRef
    from .webhook_payload import WebhookPayload
_dynamic_imports: typing.Dict[str, str] = {
    "ChatCompletionRequest": ".chat_completion_request",
    "ChatCompletionRequestLogprobs": ".chat_completion_request_logprobs",
    "ChatCompletionRequestMetadata": ".chat_completion_request_metadata",
    "ChatCompletionRequestReasoningEffort": ".chat_completion_request_reasoning_effort",
    "ChatCompletionRequestResponseFormat": ".chat_completion_request_response_format",
    "ChatCompletionRequestResponseFormatJsonSchema": ".chat_completion_request_response_format_json_schema",
    "ChatCompletionRequestResponseFormatType": ".chat_completion_request_response_format_type",
    "ChatCompletionRequestToolChoice": ".chat_completion_request_tool_choice",
    "ChatCompletionRequestToolChoiceZero": ".chat_completion_request_tool_choice_zero",
    "ChatCompletionRequestVerbosity": ".chat_completion_request_verbosity",
    "ChatCompletionResponse": ".chat_completion_response",
    "ChatCompletionResponseChoicesItem": ".chat_completion_response_choices_item",
    "ChatCompletionResponseUsage": ".chat_completion_response_usage",
    "ChatMessage": ".chat_message",
    "ChatMessageRole": ".chat_message_role",
    "CtaMatchRequest": ".cta_match_request",
    "Error": ".error",
    "SuccessResponse": ".success_response",
    "TagRef": ".tag_ref",
    "User": ".user",
    "UserFlag": ".user_flag",
    "WebhookAgentRef": ".webhook_agent_ref",
    "WebhookCta": ".webhook_cta",
    "WebhookEvaluation": ".webhook_evaluation",
    "WebhookEventInfo": ".webhook_event_info",
    "WebhookEventInfoKey": ".webhook_event_info_key",
    "WebhookNamedRef": ".webhook_named_ref",
    "WebhookNotificationRef": ".webhook_notification_ref",
    "WebhookPayload": ".webhook_payload",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ChatCompletionRequest",
    "ChatCompletionRequestLogprobs",
    "ChatCompletionRequestMetadata",
    "ChatCompletionRequestReasoningEffort",
    "ChatCompletionRequestResponseFormat",
    "ChatCompletionRequestResponseFormatJsonSchema",
    "ChatCompletionRequestResponseFormatType",
    "ChatCompletionRequestToolChoice",
    "ChatCompletionRequestToolChoiceZero",
    "ChatCompletionRequestVerbosity",
    "ChatCompletionResponse",
    "ChatCompletionResponseChoicesItem",
    "ChatCompletionResponseUsage",
    "ChatMessage",
    "ChatMessageRole",
    "CtaMatchRequest",
    "Error",
    "SuccessResponse",
    "TagRef",
    "User",
    "UserFlag",
    "WebhookAgentRef",
    "WebhookCta",
    "WebhookEvaluation",
    "WebhookEventInfo",
    "WebhookEventInfoKey",
    "WebhookNamedRef",
    "WebhookNotificationRef",
    "WebhookPayload",
]
