# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message import ChatMessage


class ChatCompletionResponseChoicesItem(UniversalBaseModel):
    index: typing.Optional[int] = None
    message: typing.Optional[ChatMessage] = None
    logprobs: typing.Optional[typing.Dict[str, typing.Any]] = None
    finish_reason: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
