# This file was auto-generated by Fern from our API Definition.

import typing

ChatCompletionRequestResponseFormatType = typing.Union[
    typing.Literal["text", "html", "json", "raw", "json_schema"], typing.Any
]
