# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_completion_request_response_format_json_schema import ChatCompletionRequestResponseFormatJsonSchema
from .chat_completion_request_response_format_type import ChatCompletionRequestResponseFormatType


class ChatCompletionRequestResponseFormat(UniversalBaseModel):
    type: typing.Optional[ChatCompletionRequestResponseFormatType] = None
    json_schema: typing.Optional[ChatCompletionRequestResponseFormatJsonSchema] = pydantic.Field(default=None)
    """
    Required when type is json_schema. Supplies the JSON Schema the structured output must conform to. Structured outputs are non-streaming.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
