# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_event_info_key import WebhookEventInfoKey


class WebhookEventInfo(UniversalBaseModel):
    key: WebhookEventInfoKey = pydantic.Field()
    """
    Stable machine-readable event key.
    """

    label: str = pydantic.Field()
    """
    Human-readable event label.
    """

    occurred_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
