# This file was auto-generated by Fern from our API Definition.

import typing

WebhookEventInfoKey = typing.Union[
    typing.Literal[
        "prompt_submit",
        "response_start",
        "response_end",
        "automations_end",
        "response_like",
        "response_flag",
        "response_feedback",
        "referral_click",
        "cta_trigger",
        "cta_click",
        "guardrail_trigger",
        "attribution_click",
        "footer_click",
        "new_user",
        "new_device",
        "new_session",
        "new_conversation",
        "error",
    ],
    typing.Any,
]
