# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.success_response import SuccessResponse
from .raw_client import AsyncRawCorpusClient, RawCorpusClient
from .types.corpus_search_request_filters import CorpusSearchRequestFilters
from .types.search_corpus_response import SearchCorpusResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CorpusClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCorpusClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCorpusClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCorpusClient
        """
        return self._raw_client

    def search_corpus(
        self,
        *,
        query: str,
        prompt_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        filters: typing.Optional[CorpusSearchRequestFilters] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchCorpusResponse:
        """
        Performs a semantic search across the agent's corpus of knowledge

        Parameters
        ----------
        query : str

        prompt_id : typing.Optional[str]

        limit : typing.Optional[int]

        filters : typing.Optional[CorpusSearchRequestFilters]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchCorpusResponse
            Search results

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.corpus.search_corpus(
            query="query",
        )
        """
        _response = self._raw_client.search_corpus(
            query=query, prompt_id=prompt_id, limit=limit, filters=filters, request_options=request_options
        )
        return _response.data

    def log_corpus_view(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records that a user viewed a specific corpus item

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            View successfully logged

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.corpus.log_corpus_view(
            model="model",
            id="id",
            prompt_id="prompt_id",
        )
        """
        _response = self._raw_client.log_corpus_view(
            model, id, prompt_id=prompt_id, user_id=user_id, request_options=request_options
        )
        return _response.data

    def log_corpus_impression(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records that a corpus item was shown to a user

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Impression successfully logged

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.corpus.log_corpus_impression(
            model="model",
            id="id",
            prompt_id="prompt_id",
        )
        """
        _response = self._raw_client.log_corpus_impression(
            model, id, prompt_id=prompt_id, user_id=user_id, request_options=request_options
        )
        return _response.data

    def log_corpus_referral_redirect(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = None,
        url: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records a referral for a corpus item and, when a `url` is supplied, issues a 302 redirect to it. Without a `url`, responds with a success message. Requires either the search API entitlement or a signed `browser_key` cookie.

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The numeric ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        url : typing.Optional[str]
            URL-encoded destination to redirect to after logging the referral.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Referral successfully logged

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.corpus.log_corpus_referral_redirect(
            model="model",
            id="id",
            prompt_id="prompt_id",
        )
        """
        _response = self._raw_client.log_corpus_referral_redirect(
            model, id, prompt_id=prompt_id, user_id=user_id, url=url, request_options=request_options
        )
        return _response.data

    def log_corpus_referral(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records that a user was referred to a corpus item

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Referral successfully logged

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.corpus.log_corpus_referral(
            model="model",
            id="id",
            prompt_id="prompt_id",
        )
        """
        _response = self._raw_client.log_corpus_referral(
            model, id, prompt_id=prompt_id, user_id=user_id, request_options=request_options
        )
        return _response.data


class AsyncCorpusClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCorpusClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCorpusClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCorpusClient
        """
        return self._raw_client

    async def search_corpus(
        self,
        *,
        query: str,
        prompt_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        filters: typing.Optional[CorpusSearchRequestFilters] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchCorpusResponse:
        """
        Performs a semantic search across the agent's corpus of knowledge

        Parameters
        ----------
        query : str

        prompt_id : typing.Optional[str]

        limit : typing.Optional[int]

        filters : typing.Optional[CorpusSearchRequestFilters]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchCorpusResponse
            Search results

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.corpus.search_corpus(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_corpus(
            query=query, prompt_id=prompt_id, limit=limit, filters=filters, request_options=request_options
        )
        return _response.data

    async def log_corpus_view(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records that a user viewed a specific corpus item

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            View successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.corpus.log_corpus_view(
                model="model",
                id="id",
                prompt_id="prompt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.log_corpus_view(
            model, id, prompt_id=prompt_id, user_id=user_id, request_options=request_options
        )
        return _response.data

    async def log_corpus_impression(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records that a corpus item was shown to a user

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Impression successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.corpus.log_corpus_impression(
                model="model",
                id="id",
                prompt_id="prompt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.log_corpus_impression(
            model, id, prompt_id=prompt_id, user_id=user_id, request_options=request_options
        )
        return _response.data

    async def log_corpus_referral_redirect(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = None,
        url: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records a referral for a corpus item and, when a `url` is supplied, issues a 302 redirect to it. Without a `url`, responds with a success message. Requires either the search API entitlement or a signed `browser_key` cookie.

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The numeric ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        url : typing.Optional[str]
            URL-encoded destination to redirect to after logging the referral.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Referral successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.corpus.log_corpus_referral_redirect(
                model="model",
                id="id",
                prompt_id="prompt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.log_corpus_referral_redirect(
            model, id, prompt_id=prompt_id, user_id=user_id, url=url, request_options=request_options
        )
        return _response.data

    async def log_corpus_referral(
        self,
        model: str,
        id: str,
        *,
        prompt_id: str,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SuccessResponse:
        """
        Records that a user was referred to a corpus item

        Parameters
        ----------
        model : str
            The model type (e.g., 'source')

        id : str
            The ID of the corpus item

        prompt_id : str

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Referral successfully logged

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.corpus.log_corpus_referral(
                model="model",
                id="id",
                prompt_id="prompt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.log_corpus_referral(
            model, id, prompt_id=prompt_id, user_id=user_id, request_options=request_options
        )
        return _response.data
