# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawConversationsClient, RawConversationsClient
from .types.get_conversation_response import GetConversationResponse
from .types.list_conversations_response import ListConversationsResponse
from .types.pause_conversation_response import PauseConversationResponse
from .types.resume_conversation_response import ResumeConversationResponse


class ConversationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConversationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConversationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConversationsClient
        """
        return self._raw_client

    def list_conversations(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConversationsResponse:
        """
        Returns a paginated list of conversations for the requesting agent, newest first.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConversationsResponse
            Paginated list of conversations

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.conversations.list_conversations()
        """
        _response = self._raw_client.list_conversations(page=page, per_page=per_page, request_options=request_options)
        return _response.data

    def get_conversation(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetConversationResponse:
        """
        Returns a single conversation by internal UUID or team-scoped external id.

        Parameters
        ----------
        id : str
            The conversation UUID or team-scoped external id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetConversationResponse
            The conversation

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.conversations.get_conversation(
            id="id",
        )
        """
        _response = self._raw_client.get_conversation(id, request_options=request_options)
        return _response.data

    def pause_conversation(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PauseConversationResponse:
        """
        Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.

        Parameters
        ----------
        id : str
            The conversation UUID or team-scoped external id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PauseConversationResponse
            Conversation paused

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.conversations.pause_conversation(
            id="id",
        )
        """
        _response = self._raw_client.pause_conversation(id, request_options=request_options)
        return _response.data

    def resume_conversation(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResumeConversationResponse:
        """
        Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.

        Parameters
        ----------
        id : str
            The conversation UUID or team-scoped external id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResumeConversationResponse
            Conversation resumed

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.conversations.resume_conversation(
            id="id",
        )
        """
        _response = self._raw_client.resume_conversation(id, request_options=request_options)
        return _response.data


class AsyncConversationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConversationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConversationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConversationsClient
        """
        return self._raw_client

    async def list_conversations(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConversationsResponse:
        """
        Returns a paginated list of conversations for the requesting agent, newest first.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConversationsResponse
            Paginated list of conversations

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conversations.list_conversations()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_conversations(
            page=page, per_page=per_page, request_options=request_options
        )
        return _response.data

    async def get_conversation(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetConversationResponse:
        """
        Returns a single conversation by internal UUID or team-scoped external id.

        Parameters
        ----------
        id : str
            The conversation UUID or team-scoped external id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetConversationResponse
            The conversation

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conversations.get_conversation(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_conversation(id, request_options=request_options)
        return _response.data

    async def pause_conversation(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PauseConversationResponse:
        """
        Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.

        Parameters
        ----------
        id : str
            The conversation UUID or team-scoped external id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PauseConversationResponse
            Conversation paused

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conversations.pause_conversation(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_conversation(id, request_options=request_options)
        return _response.data

    async def resume_conversation(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResumeConversationResponse:
        """
        Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.

        Parameters
        ----------
        id : str
            The conversation UUID or team-scoped external id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResumeConversationResponse
            Conversation resumed

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conversations.resume_conversation(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_conversation(id, request_options=request_options)
        return _response.data
