# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ChatCompletionRequest,
        ChatCompletionRequestLogprobs,
        ChatCompletionRequestMetadata,
        ChatCompletionRequestReasoningEffort,
        ChatCompletionRequestResponseFormat,
        ChatCompletionRequestResponseFormatJsonSchema,
        ChatCompletionRequestResponseFormatType,
        ChatCompletionRequestToolChoice,
        ChatCompletionRequestToolChoiceZero,
        ChatCompletionRequestVerbosity,
        ChatCompletionResponse,
        ChatCompletionResponseChoicesItem,
        ChatCompletionResponseUsage,
        ChatMessage,
        ChatMessageRole,
        CtaMatchRequest,
        Error,
        SuccessResponse,
        TagRef,
        User,
        UserFlag,
        WebhookAgentRef,
        WebhookCta,
        WebhookEvaluation,
        WebhookEventInfo,
        WebhookEventInfoKey,
        WebhookNamedRef,
        WebhookNotificationRef,
        WebhookPayload,
    )
    from .errors import (
        BadRequestError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        ServiceUnavailableError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
    from . import benchmarks, channels, chat, corpus, ct_as, evaluators, shares, users
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .benchmarks import (
        BenchmarkRunRequestContent,
        BenchmarkRunRequestReasoningEffort,
        BenchmarkRunRequestVerbosity,
        GetBenchmarkRunResponse,
        ListBenchmarkRunsResponse,
    )
    from .channels import GetDiscordChannelStatusResponse, VerifyFacebookWebhookRequestHubMode
    from .chat import GetChatCompletionResponse, ListChatCompletionsResponse
    from .client import ApologistAgentClient, AsyncApologistAgentClient
    from .corpus import CorpusSearchRequestFilters, SearchCorpusResponse
    from .ct_as import MatchCtasResponse
    from .environment import ApologistAgentClientEnvironment
    from .evaluators import (
        EvaluateContentResponse,
        EvaluatorRequestContent,
        EvaluatorRequestReasoningEffort,
        EvaluatorRequestVerbosity,
        GetEvaluationResponse,
        ListEvaluationsResponse,
    )
    from .shares import GetSharedMessagesResponse
    from .users import (
        GetUserResponse,
        ListUserFlagsResponse,
        ListUsersResponse,
        UpdateUserResponse,
        UserUpdateRequestTagsItem,
    )
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "ApologistAgentClient": ".client",
    "ApologistAgentClientEnvironment": ".environment",
    "AsyncApologistAgentClient": ".client",
    "BadRequestError": ".errors",
    "BenchmarkRunRequestContent": ".benchmarks",
    "BenchmarkRunRequestReasoningEffort": ".benchmarks",
    "BenchmarkRunRequestVerbosity": ".benchmarks",
    "ChatCompletionRequest": ".types",
    "ChatCompletionRequestLogprobs": ".types",
    "ChatCompletionRequestMetadata": ".types",
    "ChatCompletionRequestReasoningEffort": ".types",
    "ChatCompletionRequestResponseFormat": ".types",
    "ChatCompletionRequestResponseFormatJsonSchema": ".types",
    "ChatCompletionRequestResponseFormatType": ".types",
    "ChatCompletionRequestToolChoice": ".types",
    "ChatCompletionRequestToolChoiceZero": ".types",
    "ChatCompletionRequestVerbosity": ".types",
    "ChatCompletionResponse": ".types",
    "ChatCompletionResponseChoicesItem": ".types",
    "ChatCompletionResponseUsage": ".types",
    "ChatMessage": ".types",
    "ChatMessageRole": ".types",
    "CorpusSearchRequestFilters": ".corpus",
    "CtaMatchRequest": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "Error": ".types",
    "EvaluateContentResponse": ".evaluators",
    "EvaluatorRequestContent": ".evaluators",
    "EvaluatorRequestReasoningEffort": ".evaluators",
    "EvaluatorRequestVerbosity": ".evaluators",
    "ForbiddenError": ".errors",
    "GetBenchmarkRunResponse": ".benchmarks",
    "GetChatCompletionResponse": ".chat",
    "GetDiscordChannelStatusResponse": ".channels",
    "GetEvaluationResponse": ".evaluators",
    "GetSharedMessagesResponse": ".shares",
    "GetUserResponse": ".users",
    "InternalServerError": ".errors",
    "ListBenchmarkRunsResponse": ".benchmarks",
    "ListChatCompletionsResponse": ".chat",
    "ListEvaluationsResponse": ".evaluators",
    "ListUserFlagsResponse": ".users",
    "ListUsersResponse": ".users",
    "MatchCtasResponse": ".ct_as",
    "NotFoundError": ".errors",
    "SearchCorpusResponse": ".corpus",
    "ServiceUnavailableError": ".errors",
    "SuccessResponse": ".types",
    "TagRef": ".types",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "UpdateUserResponse": ".users",
    "User": ".types",
    "UserFlag": ".types",
    "UserUpdateRequestTagsItem": ".users",
    "VerifyFacebookWebhookRequestHubMode": ".channels",
    "WebhookAgentRef": ".types",
    "WebhookCta": ".types",
    "WebhookEvaluation": ".types",
    "WebhookEventInfo": ".types",
    "WebhookEventInfoKey": ".types",
    "WebhookNamedRef": ".types",
    "WebhookNotificationRef": ".types",
    "WebhookPayload": ".types",
    "__version__": ".version",
    "benchmarks": ".benchmarks",
    "channels": ".channels",
    "chat": ".chat",
    "corpus": ".corpus",
    "ct_as": ".ct_as",
    "evaluators": ".evaluators",
    "shares": ".shares",
    "users": ".users",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApologistAgentClient",
    "ApologistAgentClientEnvironment",
    "AsyncApologistAgentClient",
    "BadRequestError",
    "BenchmarkRunRequestContent",
    "BenchmarkRunRequestReasoningEffort",
    "BenchmarkRunRequestVerbosity",
    "ChatCompletionRequest",
    "ChatCompletionRequestLogprobs",
    "ChatCompletionRequestMetadata",
    "ChatCompletionRequestReasoningEffort",
    "ChatCompletionRequestResponseFormat",
    "ChatCompletionRequestResponseFormatJsonSchema",
    "ChatCompletionRequestResponseFormatType",
    "ChatCompletionRequestToolChoice",
    "ChatCompletionRequestToolChoiceZero",
    "ChatCompletionRequestVerbosity",
    "ChatCompletionResponse",
    "ChatCompletionResponseChoicesItem",
    "ChatCompletionResponseUsage",
    "ChatMessage",
    "ChatMessageRole",
    "CorpusSearchRequestFilters",
    "CtaMatchRequest",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "Error",
    "EvaluateContentResponse",
    "EvaluatorRequestContent",
    "EvaluatorRequestReasoningEffort",
    "EvaluatorRequestVerbosity",
    "ForbiddenError",
    "GetBenchmarkRunResponse",
    "GetChatCompletionResponse",
    "GetDiscordChannelStatusResponse",
    "GetEvaluationResponse",
    "GetSharedMessagesResponse",
    "GetUserResponse",
    "InternalServerError",
    "ListBenchmarkRunsResponse",
    "ListChatCompletionsResponse",
    "ListEvaluationsResponse",
    "ListUserFlagsResponse",
    "ListUsersResponse",
    "MatchCtasResponse",
    "NotFoundError",
    "SearchCorpusResponse",
    "ServiceUnavailableError",
    "SuccessResponse",
    "TagRef",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "UpdateUserResponse",
    "User",
    "UserFlag",
    "UserUpdateRequestTagsItem",
    "VerifyFacebookWebhookRequestHubMode",
    "WebhookAgentRef",
    "WebhookCta",
    "WebhookEvaluation",
    "WebhookEventInfo",
    "WebhookEventInfoKey",
    "WebhookNamedRef",
    "WebhookNotificationRef",
    "WebhookPayload",
    "__version__",
    "benchmarks",
    "channels",
    "chat",
    "corpus",
    "ct_as",
    "evaluators",
    "shares",
    "users",
]
