# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import ApologistAgentClientEnvironment

if typing.TYPE_CHECKING:
    from .agent.client import AgentClient, AsyncAgentClient
    from .benchmarks.client import AsyncBenchmarksClient, BenchmarksClient
    from .channels.client import AsyncChannelsClient, ChannelsClient
    from .chat.client import AsyncChatClient, ChatClient
    from .conversations.client import AsyncConversationsClient, ConversationsClient
    from .corpus.client import AsyncCorpusClient, CorpusClient
    from .ct_as.client import AsyncCtAsClient, CtAsClient
    from .evaluators.client import AsyncEvaluatorsClient, EvaluatorsClient
    from .shares.client import AsyncSharesClient, SharesClient
    from .users.client import AsyncUsersClient, UsersClient


class ApologistAgentClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : ApologistAgentClientEnvironment
        The environment to use for requests from the client. from .environment import ApologistAgentClientEnvironment



        Defaults to ApologistAgentClientEnvironment.DEFAULT



    domain : typing.Optional[str]
        Server URL variable for 'domain'. Defaults to 'your-agent-domain.com'.

    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from apologist import ApologistAgentClient

    client = ApologistAgentClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: ApologistAgentClientEnvironment = ApologistAgentClientEnvironment.DEFAULT,
        domain: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if domain is not None:
            _domain = domain if domain is not None else "your-agent-domain.com"
            _environment_url_templates = {
                ApologistAgentClientEnvironment.DEFAULT: "https://{domain}/api/v1",
            }
            _url_template = _environment_url_templates.get(environment, "https://{domain}/api/v1")
            if base_url is None:
                base_url = _url_template.format(domain=_domain)
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._chat: typing.Optional[ChatClient] = None
        self._corpus: typing.Optional[CorpusClient] = None
        self._evaluators: typing.Optional[EvaluatorsClient] = None
        self._ct_as: typing.Optional[CtAsClient] = None
        self._users: typing.Optional[UsersClient] = None
        self._benchmarks: typing.Optional[BenchmarksClient] = None
        self._agent: typing.Optional[AgentClient] = None
        self._conversations: typing.Optional[ConversationsClient] = None
        self._channels: typing.Optional[ChannelsClient] = None
        self._shares: typing.Optional[SharesClient] = None

    @property
    def chat(self):
        if self._chat is None:
            from .chat.client import ChatClient  # noqa: E402

            self._chat = ChatClient(client_wrapper=self._client_wrapper)
        return self._chat

    @property
    def corpus(self):
        if self._corpus is None:
            from .corpus.client import CorpusClient  # noqa: E402

            self._corpus = CorpusClient(client_wrapper=self._client_wrapper)
        return self._corpus

    @property
    def evaluators(self):
        if self._evaluators is None:
            from .evaluators.client import EvaluatorsClient  # noqa: E402

            self._evaluators = EvaluatorsClient(client_wrapper=self._client_wrapper)
        return self._evaluators

    @property
    def ct_as(self):
        if self._ct_as is None:
            from .ct_as.client import CtAsClient  # noqa: E402

            self._ct_as = CtAsClient(client_wrapper=self._client_wrapper)
        return self._ct_as

    @property
    def users(self):
        if self._users is None:
            from .users.client import UsersClient  # noqa: E402

            self._users = UsersClient(client_wrapper=self._client_wrapper)
        return self._users

    @property
    def benchmarks(self):
        if self._benchmarks is None:
            from .benchmarks.client import BenchmarksClient  # noqa: E402

            self._benchmarks = BenchmarksClient(client_wrapper=self._client_wrapper)
        return self._benchmarks

    @property
    def agent(self):
        if self._agent is None:
            from .agent.client import AgentClient  # noqa: E402

            self._agent = AgentClient(client_wrapper=self._client_wrapper)
        return self._agent

    @property
    def conversations(self):
        if self._conversations is None:
            from .conversations.client import ConversationsClient  # noqa: E402

            self._conversations = ConversationsClient(client_wrapper=self._client_wrapper)
        return self._conversations

    @property
    def channels(self):
        if self._channels is None:
            from .channels.client import ChannelsClient  # noqa: E402

            self._channels = ChannelsClient(client_wrapper=self._client_wrapper)
        return self._channels

    @property
    def shares(self):
        if self._shares is None:
            from .shares.client import SharesClient  # noqa: E402

            self._shares = SharesClient(client_wrapper=self._client_wrapper)
        return self._shares


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncApologistAgentClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : ApologistAgentClientEnvironment
        The environment to use for requests from the client. from .environment import ApologistAgentClientEnvironment



        Defaults to ApologistAgentClientEnvironment.DEFAULT



    domain : typing.Optional[str]
        Server URL variable for 'domain'. Defaults to 'your-agent-domain.com'.

    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from apologist import AsyncApologistAgentClient

    client = AsyncApologistAgentClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: ApologistAgentClientEnvironment = ApologistAgentClientEnvironment.DEFAULT,
        domain: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if domain is not None:
            _domain = domain if domain is not None else "your-agent-domain.com"
            _environment_url_templates = {
                ApologistAgentClientEnvironment.DEFAULT: "https://{domain}/api/v1",
            }
            _url_template = _environment_url_templates.get(environment, "https://{domain}/api/v1")
            if base_url is None:
                base_url = _url_template.format(domain=_domain)
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._chat: typing.Optional[AsyncChatClient] = None
        self._corpus: typing.Optional[AsyncCorpusClient] = None
        self._evaluators: typing.Optional[AsyncEvaluatorsClient] = None
        self._ct_as: typing.Optional[AsyncCtAsClient] = None
        self._users: typing.Optional[AsyncUsersClient] = None
        self._benchmarks: typing.Optional[AsyncBenchmarksClient] = None
        self._agent: typing.Optional[AsyncAgentClient] = None
        self._conversations: typing.Optional[AsyncConversationsClient] = None
        self._channels: typing.Optional[AsyncChannelsClient] = None
        self._shares: typing.Optional[AsyncSharesClient] = None

    @property
    def chat(self):
        if self._chat is None:
            from .chat.client import AsyncChatClient  # noqa: E402

            self._chat = AsyncChatClient(client_wrapper=self._client_wrapper)
        return self._chat

    @property
    def corpus(self):
        if self._corpus is None:
            from .corpus.client import AsyncCorpusClient  # noqa: E402

            self._corpus = AsyncCorpusClient(client_wrapper=self._client_wrapper)
        return self._corpus

    @property
    def evaluators(self):
        if self._evaluators is None:
            from .evaluators.client import AsyncEvaluatorsClient  # noqa: E402

            self._evaluators = AsyncEvaluatorsClient(client_wrapper=self._client_wrapper)
        return self._evaluators

    @property
    def ct_as(self):
        if self._ct_as is None:
            from .ct_as.client import AsyncCtAsClient  # noqa: E402

            self._ct_as = AsyncCtAsClient(client_wrapper=self._client_wrapper)
        return self._ct_as

    @property
    def users(self):
        if self._users is None:
            from .users.client import AsyncUsersClient  # noqa: E402

            self._users = AsyncUsersClient(client_wrapper=self._client_wrapper)
        return self._users

    @property
    def benchmarks(self):
        if self._benchmarks is None:
            from .benchmarks.client import AsyncBenchmarksClient  # noqa: E402

            self._benchmarks = AsyncBenchmarksClient(client_wrapper=self._client_wrapper)
        return self._benchmarks

    @property
    def agent(self):
        if self._agent is None:
            from .agent.client import AsyncAgentClient  # noqa: E402

            self._agent = AsyncAgentClient(client_wrapper=self._client_wrapper)
        return self._agent

    @property
    def conversations(self):
        if self._conversations is None:
            from .conversations.client import AsyncConversationsClient  # noqa: E402

            self._conversations = AsyncConversationsClient(client_wrapper=self._client_wrapper)
        return self._conversations

    @property
    def channels(self):
        if self._channels is None:
            from .channels.client import AsyncChannelsClient  # noqa: E402

            self._channels = AsyncChannelsClient(client_wrapper=self._client_wrapper)
        return self._channels

    @property
    def shares(self):
        if self._shares is None:
            from .shares.client import AsyncSharesClient  # noqa: E402

            self._shares = AsyncSharesClient(client_wrapper=self._client_wrapper)
        return self._shares


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: ApologistAgentClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
