# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.cta_match_request import CtaMatchRequest
from ..types.success_response import SuccessResponse
from .raw_client import AsyncRawCtAsClient, RawCtAsClient
from .types.match_ctas_response import MatchCtasResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CtAsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCtAsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCtAsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCtAsClient
        """
        return self._raw_client

    def match_ctas(
        self, *, request: CtaMatchRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> MatchCtasResponse:
        """
        Finds matching CTAs based on conversation context, user, session, device, or messages

        Parameters
        ----------
        request : CtaMatchRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MatchCtasResponse
            Matched CTAs

        Examples
        --------
        from apologist_agent import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.ct_as.match_ctas(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.match_ctas(request=request, request_options=request_options)
        return _response.data

    def log_cta_click(
        self, id: str, *, prompt_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Records that a user clicked on a specific CTA

        Parameters
        ----------
        id : str
            The ID of the CTA

        prompt_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Click successfully logged

        Examples
        --------
        from apologist_agent import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.ct_as.log_cta_click(
            id="id",
            prompt_id="prompt_id",
        )
        """
        _response = self._raw_client.log_cta_click(id, prompt_id=prompt_id, request_options=request_options)
        return _response.data


class AsyncCtAsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCtAsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCtAsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCtAsClient
        """
        return self._raw_client

    async def match_ctas(
        self, *, request: CtaMatchRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> MatchCtasResponse:
        """
        Finds matching CTAs based on conversation context, user, session, device, or messages

        Parameters
        ----------
        request : CtaMatchRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MatchCtasResponse
            Matched CTAs

        Examples
        --------
        import asyncio

        from apologist_agent import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.ct_as.match_ctas(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.match_ctas(request=request, request_options=request_options)
        return _response.data

    async def log_cta_click(
        self, id: str, *, prompt_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Records that a user clicked on a specific CTA

        Parameters
        ----------
        id : str
            The ID of the CTA

        prompt_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Click successfully logged

        Examples
        --------
        import asyncio

        from apologist_agent import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.ct_as.log_cta_click(
                id="id",
                prompt_id="prompt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.log_cta_click(id, prompt_id=prompt_id, request_options=request_options)
        return _response.data
