# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawEvaluatorsClient, RawEvaluatorsClient
from .types.evaluate_content_response import EvaluateContentResponse
from .types.evaluator_request_content import EvaluatorRequestContent
from .types.evaluator_request_reasoning_effort import EvaluatorRequestReasoningEffort
from .types.evaluator_request_verbosity import EvaluatorRequestVerbosity
from .types.get_evaluation_response import GetEvaluationResponse
from .types.list_evaluations_response import ListEvaluationsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EvaluatorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEvaluatorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEvaluatorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEvaluatorsClient
        """
        return self._raw_client

    def list_evaluations(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        min_duration: typing.Optional[str] = None,
        max_duration: typing.Optional[str] = None,
        min_score: typing.Optional[str] = None,
        max_score: typing.Optional[str] = None,
        passed: typing.Optional[str] = None,
        benchmark: typing.Optional[str] = None,
        benchmark_run_id: typing.Optional[str] = None,
        benchmark_question_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEvaluationsResponse:
        """
        Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        min_duration : typing.Optional[str]

        max_duration : typing.Optional[str]

        min_score : typing.Optional[str]

        max_score : typing.Optional[str]

        passed : typing.Optional[str]

        benchmark : typing.Optional[str]

        benchmark_run_id : typing.Optional[str]

        benchmark_question_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEvaluationsResponse
            Paginated list of evaluations

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.list_evaluations(
            id="id",
        )
        """
        _response = self._raw_client.list_evaluations(
            id,
            page=page,
            per_page=per_page,
            min_timestamp=min_timestamp,
            max_timestamp=max_timestamp,
            min_duration=min_duration,
            max_duration=max_duration,
            min_score=min_score,
            max_score=max_score,
            passed=passed,
            benchmark=benchmark,
            benchmark_run_id=benchmark_run_id,
            benchmark_question_id=benchmark_question_id,
            request_options=request_options,
        )
        return _response.data

    def evaluate_content(
        self,
        id: str,
        *,
        content: EvaluatorRequestContent,
        frequency_penalty: typing.Optional[float] = OMIT,
        confidence_threshold: typing.Optional[float] = OMIT,
        model: typing.Optional[str] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        reasoning_effort: typing.Optional[EvaluatorRequestReasoningEffort] = OMIT,
        verbosity: typing.Optional[EvaluatorRequestVerbosity] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluateContentResponse:
        """
        Runs an evaluation on the provided content using the specified evaluator

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        content : EvaluatorRequestContent

        frequency_penalty : typing.Optional[float]

        confidence_threshold : typing.Optional[float]

        model : typing.Optional[str]

        presence_penalty : typing.Optional[float]

        reasoning_effort : typing.Optional[EvaluatorRequestReasoningEffort]

        verbosity : typing.Optional[EvaluatorRequestVerbosity]

        temperature : typing.Optional[float]

        top_p : typing.Optional[float]

        variables : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Flat string key/value pairs substituted into `{key}` placeholders in the evaluator prompt. Reserved keys (`options`, `option_descriptions`, `criteria`) cannot be overridden. Not persisted; omitted from the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluateContentResponse
            Evaluation result

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.evaluate_content(
            id="id",
            content="content",
        )
        """
        _response = self._raw_client.evaluate_content(
            id,
            content=content,
            frequency_penalty=frequency_penalty,
            confidence_threshold=confidence_threshold,
            model=model,
            presence_penalty=presence_penalty,
            reasoning_effort=reasoning_effort,
            verbosity=verbosity,
            temperature=temperature,
            top_p=top_p,
            variables=variables,
            request_options=request_options,
        )
        return _response.data

    def get_evaluation(
        self, id: str, evaluation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetEvaluationResponse:
        """
        Returns a single evaluation for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The id or key of the evaluator

        evaluation_id : str
            The id or UUID of the evaluation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetEvaluationResponse
            The evaluation

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.evaluators.get_evaluation(
            id="id",
            evaluation_id="evaluationId",
        )
        """
        _response = self._raw_client.get_evaluation(id, evaluation_id, request_options=request_options)
        return _response.data


class AsyncEvaluatorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEvaluatorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEvaluatorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEvaluatorsClient
        """
        return self._raw_client

    async def list_evaluations(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        min_duration: typing.Optional[str] = None,
        max_duration: typing.Optional[str] = None,
        min_score: typing.Optional[str] = None,
        max_score: typing.Optional[str] = None,
        passed: typing.Optional[str] = None,
        benchmark: typing.Optional[str] = None,
        benchmark_run_id: typing.Optional[str] = None,
        benchmark_question_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEvaluationsResponse:
        """
        Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        min_duration : typing.Optional[str]

        max_duration : typing.Optional[str]

        min_score : typing.Optional[str]

        max_score : typing.Optional[str]

        passed : typing.Optional[str]

        benchmark : typing.Optional[str]

        benchmark_run_id : typing.Optional[str]

        benchmark_question_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEvaluationsResponse
            Paginated list of evaluations

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.list_evaluations(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_evaluations(
            id,
            page=page,
            per_page=per_page,
            min_timestamp=min_timestamp,
            max_timestamp=max_timestamp,
            min_duration=min_duration,
            max_duration=max_duration,
            min_score=min_score,
            max_score=max_score,
            passed=passed,
            benchmark=benchmark,
            benchmark_run_id=benchmark_run_id,
            benchmark_question_id=benchmark_question_id,
            request_options=request_options,
        )
        return _response.data

    async def evaluate_content(
        self,
        id: str,
        *,
        content: EvaluatorRequestContent,
        frequency_penalty: typing.Optional[float] = OMIT,
        confidence_threshold: typing.Optional[float] = OMIT,
        model: typing.Optional[str] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        reasoning_effort: typing.Optional[EvaluatorRequestReasoningEffort] = OMIT,
        verbosity: typing.Optional[EvaluatorRequestVerbosity] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluateContentResponse:
        """
        Runs an evaluation on the provided content using the specified evaluator

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        content : EvaluatorRequestContent

        frequency_penalty : typing.Optional[float]

        confidence_threshold : typing.Optional[float]

        model : typing.Optional[str]

        presence_penalty : typing.Optional[float]

        reasoning_effort : typing.Optional[EvaluatorRequestReasoningEffort]

        verbosity : typing.Optional[EvaluatorRequestVerbosity]

        temperature : typing.Optional[float]

        top_p : typing.Optional[float]

        variables : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Flat string key/value pairs substituted into `{key}` placeholders in the evaluator prompt. Reserved keys (`options`, `option_descriptions`, `criteria`) cannot be overridden. Not persisted; omitted from the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluateContentResponse
            Evaluation result

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.evaluate_content(
                id="id",
                content="content",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.evaluate_content(
            id,
            content=content,
            frequency_penalty=frequency_penalty,
            confidence_threshold=confidence_threshold,
            model=model,
            presence_penalty=presence_penalty,
            reasoning_effort=reasoning_effort,
            verbosity=verbosity,
            temperature=temperature,
            top_p=top_p,
            variables=variables,
            request_options=request_options,
        )
        return _response.data

    async def get_evaluation(
        self, id: str, evaluation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetEvaluationResponse:
        """
        Returns a single evaluation for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The id or key of the evaluator

        evaluation_id : str
            The id or UUID of the evaluation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetEvaluationResponse
            The evaluation

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.evaluators.get_evaluation(
                id="id",
                evaluation_id="evaluationId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_evaluation(id, evaluation_id, request_options=request_options)
        return _response.data
