# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.error import Error
from .types.evaluate_content_response import EvaluateContentResponse
from .types.evaluator_request_content import EvaluatorRequestContent
from .types.evaluator_request_reasoning_effort import EvaluatorRequestReasoningEffort
from .types.evaluator_request_verbosity import EvaluatorRequestVerbosity
from .types.get_evaluation_response import GetEvaluationResponse
from .types.list_evaluations_response import ListEvaluationsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawEvaluatorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_evaluations(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        min_duration: typing.Optional[str] = None,
        max_duration: typing.Optional[str] = None,
        min_score: typing.Optional[str] = None,
        max_score: typing.Optional[str] = None,
        passed: typing.Optional[str] = None,
        benchmark: typing.Optional[str] = None,
        benchmark_run_id: typing.Optional[str] = None,
        benchmark_question_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListEvaluationsResponse]:
        """
        Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        min_duration : typing.Optional[str]

        max_duration : typing.Optional[str]

        min_score : typing.Optional[str]

        max_score : typing.Optional[str]

        passed : typing.Optional[str]

        benchmark : typing.Optional[str]

        benchmark_run_id : typing.Optional[str]

        benchmark_question_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListEvaluationsResponse]
            Paginated list of evaluations
        """
        _response = self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(id)}/evaluations",
            method="GET",
            params={
                "page": page,
                "per_page": per_page,
                "min_timestamp": min_timestamp,
                "max_timestamp": max_timestamp,
                "min_duration": min_duration,
                "max_duration": max_duration,
                "min_score": min_score,
                "max_score": max_score,
                "passed": passed,
                "benchmark": benchmark,
                "benchmark_run_id": benchmark_run_id,
                "benchmark_question_id": benchmark_question_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListEvaluationsResponse,
                    parse_obj_as(
                        type_=ListEvaluationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def evaluate_content(
        self,
        id: str,
        *,
        content: EvaluatorRequestContent,
        frequency_penalty: typing.Optional[float] = OMIT,
        confidence_threshold: typing.Optional[float] = OMIT,
        model: typing.Optional[str] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        reasoning_effort: typing.Optional[EvaluatorRequestReasoningEffort] = OMIT,
        verbosity: typing.Optional[EvaluatorRequestVerbosity] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EvaluateContentResponse]:
        """
        Runs an evaluation on the provided content using the specified evaluator

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        content : EvaluatorRequestContent

        frequency_penalty : typing.Optional[float]

        confidence_threshold : typing.Optional[float]

        model : typing.Optional[str]

        presence_penalty : typing.Optional[float]

        reasoning_effort : typing.Optional[EvaluatorRequestReasoningEffort]

        verbosity : typing.Optional[EvaluatorRequestVerbosity]

        temperature : typing.Optional[float]

        top_p : typing.Optional[float]

        variables : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Flat string key/value pairs substituted into `{key}` placeholders in the evaluator prompt. Reserved keys (`options`, `option_descriptions`, `criteria`) cannot be overridden. Not persisted; omitted from the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvaluateContentResponse]
            Evaluation result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(id)}/evaluations",
            method="POST",
            json={
                "frequency_penalty": frequency_penalty,
                "confidence_threshold": confidence_threshold,
                "content": convert_and_respect_annotation_metadata(
                    object_=content, annotation=EvaluatorRequestContent, direction="write"
                ),
                "model": model,
                "presence_penalty": presence_penalty,
                "reasoning_effort": reasoning_effort,
                "verbosity": verbosity,
                "temperature": temperature,
                "top_p": top_p,
                "variables": variables,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluateContentResponse,
                    parse_obj_as(
                        type_=EvaluateContentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_evaluation(
        self, id: str, evaluation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetEvaluationResponse]:
        """
        Returns a single evaluation for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The id or key of the evaluator

        evaluation_id : str
            The id or UUID of the evaluation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetEvaluationResponse]
            The evaluation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(id)}/evaluations/{encode_path_param(evaluation_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetEvaluationResponse,
                    parse_obj_as(
                        type_=GetEvaluationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawEvaluatorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_evaluations(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        min_timestamp: typing.Optional[str] = None,
        max_timestamp: typing.Optional[str] = None,
        min_duration: typing.Optional[str] = None,
        max_duration: typing.Optional[str] = None,
        min_score: typing.Optional[str] = None,
        max_score: typing.Optional[str] = None,
        passed: typing.Optional[str] = None,
        benchmark: typing.Optional[str] = None,
        benchmark_run_id: typing.Optional[str] = None,
        benchmark_question_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListEvaluationsResponse]:
        """
        Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        page : typing.Optional[int]

        per_page : typing.Optional[int]
            Results per page (clamped to 100).

        min_timestamp : typing.Optional[str]

        max_timestamp : typing.Optional[str]

        min_duration : typing.Optional[str]

        max_duration : typing.Optional[str]

        min_score : typing.Optional[str]

        max_score : typing.Optional[str]

        passed : typing.Optional[str]

        benchmark : typing.Optional[str]

        benchmark_run_id : typing.Optional[str]

        benchmark_question_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListEvaluationsResponse]
            Paginated list of evaluations
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(id)}/evaluations",
            method="GET",
            params={
                "page": page,
                "per_page": per_page,
                "min_timestamp": min_timestamp,
                "max_timestamp": max_timestamp,
                "min_duration": min_duration,
                "max_duration": max_duration,
                "min_score": min_score,
                "max_score": max_score,
                "passed": passed,
                "benchmark": benchmark,
                "benchmark_run_id": benchmark_run_id,
                "benchmark_question_id": benchmark_question_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListEvaluationsResponse,
                    parse_obj_as(
                        type_=ListEvaluationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def evaluate_content(
        self,
        id: str,
        *,
        content: EvaluatorRequestContent,
        frequency_penalty: typing.Optional[float] = OMIT,
        confidence_threshold: typing.Optional[float] = OMIT,
        model: typing.Optional[str] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        reasoning_effort: typing.Optional[EvaluatorRequestReasoningEffort] = OMIT,
        verbosity: typing.Optional[EvaluatorRequestVerbosity] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        top_p: typing.Optional[float] = OMIT,
        variables: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EvaluateContentResponse]:
        """
        Runs an evaluation on the provided content using the specified evaluator

        Parameters
        ----------
        id : str
            The ID or key of the evaluator

        content : EvaluatorRequestContent

        frequency_penalty : typing.Optional[float]

        confidence_threshold : typing.Optional[float]

        model : typing.Optional[str]

        presence_penalty : typing.Optional[float]

        reasoning_effort : typing.Optional[EvaluatorRequestReasoningEffort]

        verbosity : typing.Optional[EvaluatorRequestVerbosity]

        temperature : typing.Optional[float]

        top_p : typing.Optional[float]

        variables : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Flat string key/value pairs substituted into `{key}` placeholders in the evaluator prompt. Reserved keys (`options`, `option_descriptions`, `criteria`) cannot be overridden. Not persisted; omitted from the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvaluateContentResponse]
            Evaluation result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(id)}/evaluations",
            method="POST",
            json={
                "frequency_penalty": frequency_penalty,
                "confidence_threshold": confidence_threshold,
                "content": convert_and_respect_annotation_metadata(
                    object_=content, annotation=EvaluatorRequestContent, direction="write"
                ),
                "model": model,
                "presence_penalty": presence_penalty,
                "reasoning_effort": reasoning_effort,
                "verbosity": verbosity,
                "temperature": temperature,
                "top_p": top_p,
                "variables": variables,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvaluateContentResponse,
                    parse_obj_as(
                        type_=EvaluateContentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_evaluation(
        self, id: str, evaluation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetEvaluationResponse]:
        """
        Returns a single evaluation for the evaluator, scoped to the requesting agent.

        Parameters
        ----------
        id : str
            The id or key of the evaluator

        evaluation_id : str
            The id or UUID of the evaluation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetEvaluationResponse]
            The evaluation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"evaluators/{encode_path_param(id)}/evaluations/{encode_path_param(evaluation_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetEvaluationResponse,
                    parse_obj_as(
                        type_=GetEvaluationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
