# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSharesClient, RawSharesClient
from .types.get_shared_messages_response import GetSharedMessagesResponse


class SharesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSharesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSharesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSharesClient
        """
        return self._raw_client

    def get_shared_messages(
        self, token: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSharedMessagesResponse:
        """
        Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.

        Parameters
        ----------
        token : str
            The share token

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSharedMessagesResponse
            The shared messages

        Examples
        --------
        from apologist_agent import ApologistAgent

        client = ApologistAgent(
            api_key="YOUR_API_KEY",
        )
        client.shares.get_shared_messages(
            token="token",
        )
        """
        _response = self._raw_client.get_shared_messages(token, request_options=request_options)
        return _response.data


class AsyncSharesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSharesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSharesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSharesClient
        """
        return self._raw_client

    async def get_shared_messages(
        self, token: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSharedMessagesResponse:
        """
        Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.

        Parameters
        ----------
        token : str
            The share token

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSharedMessagesResponse
            The shared messages

        Examples
        --------
        import asyncio

        from apologist_agent import AsyncApologistAgent

        client = AsyncApologistAgent(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.shares.get_shared_messages(
                token="token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_shared_messages(token, request_options=request_options)
        return _response.data
