# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .anonymize_user_response import AnonymizeUserResponse
    from .get_user_response import GetUserResponse
    from .list_user_flags_response import ListUserFlagsResponse
    from .list_users_response import ListUsersResponse
    from .scrub_user_response import ScrubUserResponse
    from .update_user_response import UpdateUserResponse
    from .user_update_request_tags_item import UserUpdateRequestTagsItem
_dynamic_imports: typing.Dict[str, str] = {
    "AnonymizeUserResponse": ".anonymize_user_response",
    "GetUserResponse": ".get_user_response",
    "ListUserFlagsResponse": ".list_user_flags_response",
    "ListUsersResponse": ".list_users_response",
    "ScrubUserResponse": ".scrub_user_response",
    "UpdateUserResponse": ".update_user_response",
    "UserUpdateRequestTagsItem": ".user_update_request_tags_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AnonymizeUserResponse",
    "GetUserResponse",
    "ListUserFlagsResponse",
    "ListUsersResponse",
    "ScrubUserResponse",
    "UpdateUserResponse",
    "UserUpdateRequestTagsItem",
]
