# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawChannelsClient, RawChannelsClient
from .types.get_discord_channel_status_response import GetDiscordChannelStatusResponse
from .types.verify_facebook_webhook_request_hub_mode import VerifyFacebookWebhookRequestHubMode

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChannelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChannelsClient
        """
        return self._raw_client

    def get_discord_channel_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetDiscordChannelStatusResponse:
        """
        Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.

        Parameters
        ----------
        id : str
            The channel id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDiscordChannelStatusResponse
            Channel status

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.get_discord_channel_status(
            id="id",
        )
        """
        _response = self._raw_client.get_discord_channel_status(id, request_options=request_options)
        return _response.data

    def receive_discord_interaction(
        self,
        id: str,
        *,
        signature_ed25519: str,
        signature_timestamp: str,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Receives Discord interaction callbacks for the channel. Requests are verified via Ed25519 signature headers; unsigned or invalid requests are rejected. Payload shape is defined by Discord.

        Parameters
        ----------
        id : str
            The channel id

        signature_ed25519 : str
            Discord request signature (hex).

        signature_timestamp : str
            Discord request timestamp.

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.receive_discord_interaction(
            id="id",
            signature_ed25519="x-signature-ed25519",
            signature_timestamp="x-signature-timestamp",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.receive_discord_interaction(
            id,
            signature_ed25519=signature_ed25519,
            signature_timestamp=signature_timestamp,
            request=request,
            request_options=request_options,
        )
        return _response.data

    def verify_facebook_webhook(
        self,
        id: str,
        *,
        hub_mode: VerifyFacebookWebhookRequestHubMode,
        hub_verify_token: str,
        hub_challenge: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> str:
        """
        Handles the Meta webhook verification handshake, echoing `hub.challenge` when `hub.verify_token` matches the channel's configured token.

        Parameters
        ----------
        id : str
            The channel id

        hub_mode : VerifyFacebookWebhookRequestHubMode

        hub_verify_token : str

        hub_challenge : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Verification succeeded; echoes the challenge

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.verify_facebook_webhook(
            id="id",
            hub_mode="subscribe",
            hub_verify_token="hub.verify_token",
        )
        """
        _response = self._raw_client.verify_facebook_webhook(
            id,
            hub_mode=hub_mode,
            hub_verify_token=hub_verify_token,
            hub_challenge=hub_challenge,
            request_options=request_options,
        )
        return _response.data

    def receive_facebook_message(
        self, id: str, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Receives Facebook/Messenger (and Instagram-style) message events for the channel. Payload shape is defined by Meta.

        Parameters
        ----------
        id : str
            The channel id

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.receive_facebook_message(
            id="id",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.receive_facebook_message(id, request=request, request_options=request_options)
        return _response.data

    def get_instagram_privacy_policy(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        Returns a static HTML privacy policy page for the Instagram integration.

        Parameters
        ----------
        id : str
            The channel id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Privacy policy HTML

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.get_instagram_privacy_policy(
            id="id",
        )
        """
        _response = self._raw_client.get_instagram_privacy_policy(id, request_options=request_options)
        return _response.data

    def receive_telegram_update(
        self, id: str, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Receives Telegram bot update events for the channel. Non-message updates are acknowledged and ignored. Payload shape is defined by Telegram.

        Parameters
        ----------
        id : str
            The channel id

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.receive_telegram_update(
            id="id",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.receive_telegram_update(id, request=request, request_options=request_options)
        return _response.data

    def receive_twilio_message(
        self,
        id: str,
        *,
        from_: typing.Optional[str] = OMIT,
        body: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.

        Parameters
        ----------
        id : str
            The channel id

        from_ : typing.Optional[str]

        body : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from apologist import ApologistAgentClient

        client = ApologistAgentClient(
            api_key="YOUR_API_KEY",
        )
        client.channels.receive_twilio_message(
            id="id",
        )
        """
        _response = self._raw_client.receive_twilio_message(id, from_=from_, body=body, request_options=request_options)
        return _response.data


class AsyncChannelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChannelsClient
        """
        return self._raw_client

    async def get_discord_channel_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetDiscordChannelStatusResponse:
        """
        Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.

        Parameters
        ----------
        id : str
            The channel id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDiscordChannelStatusResponse
            Channel status

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.get_discord_channel_status(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_discord_channel_status(id, request_options=request_options)
        return _response.data

    async def receive_discord_interaction(
        self,
        id: str,
        *,
        signature_ed25519: str,
        signature_timestamp: str,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Receives Discord interaction callbacks for the channel. Requests are verified via Ed25519 signature headers; unsigned or invalid requests are rejected. Payload shape is defined by Discord.

        Parameters
        ----------
        id : str
            The channel id

        signature_ed25519 : str
            Discord request signature (hex).

        signature_timestamp : str
            Discord request timestamp.

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.receive_discord_interaction(
                id="id",
                signature_ed25519="x-signature-ed25519",
                signature_timestamp="x-signature-timestamp",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.receive_discord_interaction(
            id,
            signature_ed25519=signature_ed25519,
            signature_timestamp=signature_timestamp,
            request=request,
            request_options=request_options,
        )
        return _response.data

    async def verify_facebook_webhook(
        self,
        id: str,
        *,
        hub_mode: VerifyFacebookWebhookRequestHubMode,
        hub_verify_token: str,
        hub_challenge: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> str:
        """
        Handles the Meta webhook verification handshake, echoing `hub.challenge` when `hub.verify_token` matches the channel's configured token.

        Parameters
        ----------
        id : str
            The channel id

        hub_mode : VerifyFacebookWebhookRequestHubMode

        hub_verify_token : str

        hub_challenge : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Verification succeeded; echoes the challenge

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.verify_facebook_webhook(
                id="id",
                hub_mode="subscribe",
                hub_verify_token="hub.verify_token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_facebook_webhook(
            id,
            hub_mode=hub_mode,
            hub_verify_token=hub_verify_token,
            hub_challenge=hub_challenge,
            request_options=request_options,
        )
        return _response.data

    async def receive_facebook_message(
        self, id: str, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Receives Facebook/Messenger (and Instagram-style) message events for the channel. Payload shape is defined by Meta.

        Parameters
        ----------
        id : str
            The channel id

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.receive_facebook_message(
                id="id",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.receive_facebook_message(
            id, request=request, request_options=request_options
        )
        return _response.data

    async def get_instagram_privacy_policy(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> str:
        """
        Returns a static HTML privacy policy page for the Instagram integration.

        Parameters
        ----------
        id : str
            The channel id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            Privacy policy HTML

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.get_instagram_privacy_policy(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_instagram_privacy_policy(id, request_options=request_options)
        return _response.data

    async def receive_telegram_update(
        self, id: str, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Receives Telegram bot update events for the channel. Non-message updates are acknowledged and ignored. Payload shape is defined by Telegram.

        Parameters
        ----------
        id : str
            The channel id

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.receive_telegram_update(
                id="id",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.receive_telegram_update(id, request=request, request_options=request_options)
        return _response.data

    async def receive_twilio_message(
        self,
        id: str,
        *,
        from_: typing.Optional[str] = OMIT,
        body: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.

        Parameters
        ----------
        id : str
            The channel id

        from_ : typing.Optional[str]

        body : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from apologist import AsyncApologistAgentClient

        client = AsyncApologistAgentClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.receive_twilio_message(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.receive_twilio_message(
            id, from_=from_, body=body, request_options=request_options
        )
        return _response.data
