# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentPauseState(UniversalBaseModel):
    """
    Agent-wide pause or resume result, including fan-out counts.
    """

    is_paused: typing.Optional[bool] = None
    paused_at: typing.Optional[str] = None
    resumed_at: typing.Optional[str] = None
    emitted: typing.Optional[int] = pydantic.Field(default=None)
    """
    Conversations that received a transition message.
    """

    skipped: typing.Optional[int] = pydantic.Field(default=None)
    """
    Conversations skipped during fan-out.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
