# This file was auto-generated by Fern from our API Definition.

import typing

from .chat_completion_request_tool_choice_zero import ChatCompletionRequestToolChoiceZero

ChatCompletionRequestToolChoice = typing.Union[
    ChatCompletionRequestToolChoiceZero, typing.Optional[typing.Dict[str, typing.Any]]
]
