# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChatCompletionRequestMetadata(UniversalBaseModel):
    anonymous: typing.Optional[bool] = None
    conversation: typing.Optional[str] = None
    language: typing.Optional[str] = None
    max_memories: typing.Optional[int] = None
    parent_url: typing.Optional[str] = None
    parent_host: typing.Optional[str] = None
    session: typing.Optional[str] = None
    device: typing.Optional[str] = None
    referral_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Acquisition / campaign referral code stored on the user first-write-wins. Empty values are ignored; an existing user referral_code is never overwritten. The Agent UI maps ?ref=, then ?referral_code=, then ?utm_campaign= into this field.
    """

    shared_prompt: typing.Optional[int] = None
    translation: typing.Optional[str] = None
    variables: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    String key/value pairs substituted into `{key}` placeholders in the assembled system prompt. Never persisted; omitted from response metadata. Reserved system keys (language, bible, translation, passages, date/geo tokens) cannot be overridden.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
