# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Conversation(UniversalBaseModel):
    """
    A conversation scoped to the requesting agent.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Internal conversation id (UUID).
    """

    external_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Team-scoped external conversation id.
    """

    agent_id: typing.Optional[int] = None
    team_id: typing.Optional[int] = None
    tags: typing.Optional[typing.Dict[str, typing.Any]] = None
    started_at: typing.Optional[str] = None
    ended_at: typing.Optional[str] = None
    agent_paused: typing.Optional[bool] = None
    agent_paused_at: typing.Optional[str] = None
    agent_resumed_at: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
