# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UserFlag(UniversalBaseModel):
    """
    A team-level user flag definition from the user_flags table.
    """

    id: typing.Optional[int] = None
    name: typing.Optional[str] = None
    user_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Upstream owning user id when present (mirrored from Ignite).
    """

    team_id: typing.Optional[int] = None
    synced_at: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
