# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tag_ref import TagRef


class User(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Internal user id (UUID).
    """

    external_id: typing.Optional[str] = None
    team_id: typing.Optional[int] = None
    created_at: typing.Optional[str] = None
    migrated_at: typing.Optional[str] = None
    migrated_to_user_id: typing.Optional[str] = None
    tags: typing.Optional[typing.List[TagRef]] = None
    responder_id: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
