# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_redact_response_mode import UserRedactResponseMode


class UserRedactResponse(UniversalBaseModel):
    """
    Result of scrubbing or anonymizing a user's message-adjacent text. Rows and identifiers are kept.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Internal user id (UUID).
    """

    mode: typing.Optional[UserRedactResponseMode] = None
    redact_requested_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the erase request was stamped. The hourly cron finishes leftover rows.
    """

    messages_redacted: typing.Optional[int] = pydantic.Field(default=None)
    """
    Message rows rewritten in this request.
    """

    remaining: typing.Optional[int] = pydantic.Field(default=None)
    """
    Message rows still waiting. Zero means this request finished the user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
