# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_agent_ref import WebhookAgentRef
from .webhook_cta import WebhookCta
from .webhook_evaluation import WebhookEvaluation
from .webhook_event_info import WebhookEventInfo
from .webhook_named_ref import WebhookNamedRef
from .webhook_notification_ref import WebhookNotificationRef


class WebhookPayload(UniversalBaseModel):
    """
    Canonical JSON body POSTed to a configured webhook URL. `notification`, `event`, and `agent` are always present; the remaining sections appear only when relevant to the event. Treat the payload as additive and ignore unrecognised fields.
    """

    notification: WebhookNotificationRef
    event: WebhookEventInfo
    agent: WebhookAgentRef
    completion: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Present when the event is tied to a prompt. Includes the prompt and response plus `automations` and `tags` arrays. Shape mirrors the prompt API object.
    """

    channel: typing.Optional[WebhookNamedRef] = pydantic.Field(default=None)
    """
    Present when the prompt arrived via a channel.
    """

    platform: typing.Optional[WebhookNamedRef] = pydantic.Field(default=None)
    """
    Present alongside `channel` when the channel has a platform.
    """

    cta: typing.Optional[WebhookCta] = pydantic.Field(default=None)
    """
    Present for cta_trigger and cta_click events.
    """

    guardrail: typing.Optional[WebhookNamedRef] = pydantic.Field(default=None)
    """
    Present for guardrail_trigger events.
    """

    evaluator: typing.Optional[WebhookNamedRef] = pydantic.Field(default=None)
    """
    Present for CTA/guardrail events that ran an evaluation.
    """

    evaluation: typing.Optional[WebhookEvaluation] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
